source "https://rubygems.org"

gem "opal-js_wrap-three"
# This gem should work with any recent version of Opal (no guarantees),
# but it's strongly recommended to use Opal v1.4 for improved error
# reporting.
gem "opal"
gem "rack"
gem "webrick"
